version: '3'

services:
  db:
    image: postgres:10-alpine
    env_file: .env
    ports:
      - "5432"
  web:
    build:
      context: .
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
  redis:
    image: redis:alpine

  celery:
    restart: always
    build: .
    env_file: .env
    command: celery -A omni worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - django
      - redis



