# Generated by Django 3.0 on 2021-10-20 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_column='number', help_text='Number', max_length=50, unique=True, verbose_name='Number')),
                ('status', models.CharField(choices=[('created', 'created'), ('paid', 'paid'), ('sent', 'sent')], db_column='status', help_text='Status', max_length=20, verbose_name='Status')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='Date', help_text='Date Order', verbose_name='Date')),
                ('price', models.DecimalField(db_column='price', decimal_places=2, default=0, help_text='Price', max_digits=5, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'shop_order',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_column='number', help_text='Number', max_length=50, unique=True, verbose_name='Number')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='Date', help_text='Date Payment', verbose_name='Date')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], db_column='status', help_text='Status', max_length=20, verbose_name='Status')),
                ('date_confirm', models.DateField(blank=True, db_column='date_confirm', help_text='Date Confirm', null=True, verbose_name='Date Confirm')),
                ('type', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], db_column='type', help_text='Type', max_length=20, verbose_name='Type')),
                ('value', models.DecimalField(db_column='value', decimal_places=2, default=0.0, help_text='Value', max_digits=5, verbose_name='Value')),
                ('provider', models.CharField(db_column='provider', help_text='Provider', max_length=100, verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'shop_payment',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', help_text='Name', max_length=50, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(db_column='is_active', default=True, help_text='if active = True is shown in the available list', verbose_name='Active')),
                ('quantity', models.PositiveIntegerField(db_column='quantity', default=1, help_text='Quantity', verbose_name='Quantity')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'shop_product',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_column='number', help_text='Number', max_length=50, unique=True, verbose_name='Number')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='Date', help_text='Date Shipment', verbose_name='Date')),
                ('status', models.CharField(choices=[('created', 'created'), ('sent', 'sent'), ('received', 'received')], db_column='status', help_text='Status', max_length=20, verbose_name='Status')),
                ('received', models.BooleanField(db_column='is_received', default=False, help_text='Is Received', verbose_name='Is Received')),
                ('name_received', models.CharField(db_column='name_received', help_text='Date Received', max_length=250, verbose_name='Name Received')),
                ('date_received', models.DateField(db_column='date_received', help_text='Date Received', verbose_name='Date Received')),
                ('mobile_phone_received', models.CharField(db_column='mobile_phone_received', help_text='Mobile Phone', max_length=10, validators=[django.core.validators.RegexValidator('^[\\+]?[0-9]+$', 'only characters, 0-9')], verbose_name='Mobile Phone')),
                ('direction_received', models.CharField(db_column='direction_received', help_text='Direction', max_length=250, verbose_name='Direction')),
                ('city_received', models.CharField(db_column='city_received', help_text='City', max_length=50, verbose_name='City')),
                ('postal_code_received', models.CharField(db_column='postal_code_received', help_text='Postal Code', max_length=20, verbose_name='Postal Code')),
                ('order', models.ForeignKey(db_column='order_id', help_text='Shipment', on_delete=django.db.models.deletion.CASCADE, related_name='shop_shipment', related_query_name='shop_shipments', to='shop.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'db_table': 'shop_shipment',
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(db_column='value', decimal_places=2, default=0.0, help_text='Value', max_digits=5, verbose_name='Value')),
                ('order', models.ForeignKey(db_column='order_id', help_text='Order', on_delete=django.db.models.deletion.CASCADE, related_name='shop_payment_order', related_query_name='shop_payment_orders', to='shop.Order', verbose_name='Order')),
                ('payment', models.ForeignKey(db_column='payment_id', help_text='Payment', on_delete=django.db.models.deletion.CASCADE, related_name='shop_payment_order', related_query_name='shop_payment_orders', to='shop.Payment', verbose_name='Payment')),
            ],
            options={
                'verbose_name': 'Payment Order',
                'verbose_name_plural': 'Payment Orders',
                'db_table': 'shop_payment_order',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_column='quantity', default=1, help_text='Quantity', verbose_name='Quantity')),
                ('value', models.DecimalField(db_column='value', decimal_places=2, default=0.0, help_text='Value', max_digits=5, verbose_name='Value')),
                ('order', models.ForeignKey(db_column='order_id', help_text='Order', on_delete=django.db.models.deletion.CASCADE, related_name='shop_order_detail', related_query_name='shop_order_details', to='shop.Order', verbose_name='Order')),
                ('product', models.ForeignKey(db_column='product_id', help_text='Product', on_delete=django.db.models.deletion.CASCADE, related_name='shop_order_detail', related_query_name='shop_order_details', to='shop.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order Detail',
                'verbose_name_plural': 'Order Details',
                'db_table': 'shop_order_detail',
            },
        ),
    ]
