# Generated by Django 3.0 on 2021-10-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
