# Generated by Django 3.0 on 2021-10-21 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_remove_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, default=0.0, help_text='Price', max_digits=5, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, db_column='client_id', help_text='Client', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_order', related_query_name='shop_orders', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, db_column='number', help_text='Number', max_length=50, null=True, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, db_column='status', help_text='Status', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
