# Generated by Django 3.0 on 2021-10-24 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_auto_20211021_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(db_column='client_id', default=1, help_text='Client', on_delete=django.db.models.deletion.CASCADE, related_name='shop_payment', related_query_name='shop_payments', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(db_column='status', help_text='Status', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(db_column='type', help_text='Type', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=3, default=0.0, help_text='Price', max_digits=5, verbose_name='Price'),
        ),
    ]
