# Generated by Django 3.0 on 2021-10-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211024_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='date_send',
            field=models.DateField(blank=True, db_column='date_send', help_text='Date Received', null=True, verbose_name='Date Send'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date_received',
            field=models.DateField(blank=True, db_column='date_received', help_text='Date Received', null=True, verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(db_column='status', help_text='Status', max_length=20, verbose_name='Status'),
        ),
    ]
