# Generated by Django 3.0 on 2021-10-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211025_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, db_column='status', help_text='Status', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
