# Generated by Django 3.0 on 2021-10-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211025_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='number',
            field=models.CharField(blank=True, db_column='number', help_text='Number', max_length=50, null=True, unique=True, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(blank=True, db_column='status', help_text='Status', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
